[WIP] Heroku demo
IntroCept/paale-dai pull request #3
Opened 2017-02-11 08:42 UTC by ojhaujjwal

2017-02-11 10:53 UTC, geshan requested changes
Need some changes

2017-02-11 10:53 UTC, geshan commented on .gitignore
> +/demo/.env
BL

2017-02-11 10:53 UTC, geshan commented on demo/Dockerfile
> +FROM mhart/alpine-node:6.8
7.4?

2017-02-11 10:53 UTC, geshan commented on demo/Dockerfile
> +RUN chown -R root:root /var/www/paale-dai\
Nobody:nobody?

2017-02-11 17:24 UTC, ojhaujjwal commented on demo/Dockerfile
> +FROM mhart/alpine-node:6.8
+1

2017-02-11 17:26 UTC, ojhaujjwal commented on demo/Dockerfile
> +RUN chown -R root:root /var/www/paale-dai\
sorry. I didnt' get you!

2017-02-12 02:20 UTC, geshan commented on demo/Dockerfile
> +RUN chown -R root:root /var/www/paale-dai\
Root:root is not ideal, either create a user or use nobody: nobody depending on Linux flavor.

2017-02-12 10:54 UTC, ojhaujjwal commented on demo/deploy.sh
> +docker push registry.heroku.com/paale-dai/web
TODO: query health check endpoint using curl.

2017-02-12 12:15 UTC, merged